mal_moduleXs =[

	['apisetschema.dll', 'crypt32.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msasn1.dll', 'msctf.dll', 'msvcrt.dll', 'ntdll.dll', 'ole32.dll', 'rpcrt4.dll', 'user32.dll', 'usp10.dll', 'wintrust.dll'],
	['advapi32.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcrt.dll', 'nsi.dll', 'ntdll.dll', 'rasapi32.dll', 'rasman.dll', 'rpcrt4.dll', 'rtutils.dll', 'sechost.dll', 'user32.dll', 'usp10.dll', 'version.dll', 'ws2_32.dll'],
	['advapi32.dll', 'apisetschema.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcrt.dll', 'nsi.dll', 'ntdll.dll', 'rasapi32.dll', 'rasman.dll', 'rpcrt4.dll', 'rtutils.dll', 'sechost.dll', 'user32.dll', 'usp10.dll', 'version.dll', 'ws2_32.dll'],
	['advapi32.dll', 'apisetschema.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcrt.dll', 'nsi.dll', 'ntdll.dll', 'rasapi32.dll', 'rasman.dll', 'rpcrt4.dll', 'rtutils.dll', 'sechost.dll', 'user32.dll', 'usp10.dll', 'ws2_32.dll'],
	['advapi32.dll', 'apisetschema.dll', 'atl.dll', 'authz.dll', 'browcli.dll', 'clbcatq.dll', 'comctl32.dll', 'crypt32.dll', 'cryptbase.dll', 'cryptsp.dll', 'cscapi.dll', 'davclnt.dll', 'davhlpr.dll', 'dnsapi.dll', 'drprov.dll', 'dsrole.dll', 'gdi32.dll', 'iertutil.dll', 'imm32.dll', 'iphlpapi.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'mpr.dll', 'msasn1.dll', 'msctf.dll', 'msvcrt.dll', 'mswsock.dll', 'msxml3.dll', 'msxml3r.dll', 'netapi32.dll', 'netutils.dll', 'nlaapi.dll', 'normaliz.dll', 'nsi.dll', 'ntdll.dll', 'ntlanman.dll', 'ntmarta.dll', 'ole32.dll', 'oleaut32.dll', 'peerdist.dll', 'profapi.dll', 'rasadhlp.dll', 'rasapi32.dll', 'rasman.dll', 'rpcrt4.dll', 'rpcrtremote.dll', 'rsaenh.dll', 'rtutils.dll', 'sechost.dll', 'sensapi.dll', 'shell32.dll', 'shlwapi.dll', 'srvcli.dll', 'sspicli.dll', 'urlmon.dll', 'user32.dll', 'userenv.dll', 'usp10.dll', 'uxtheme.dll', 'vboxmrxnp.dll', 'vss_ps.dll', 'vssapi.dll', 'vsstrace.dll', 'wininet.dll', 'winnsi.dll', 'winsta.dll', 'wkscli.dll', 'wldap32.dll', 'ws2_32.dll', 'wshtcpip.dll'],
	['advapi32.dll', 'apisetschema.dll', 'atl.dll', 'authz.dll', 'browcli.dll', 'clbcatq.dll', 'comctl32.dll', 'crypt32.dll', 'cryptbase.dll', 'cryptsp.dll', 'cscapi.dll', 'davclnt.dll', 'davhlpr.dll', 'dnsapi.dll', 'drprov.dll', 'dsrole.dll', 'gdi32.dll', 'iertutil.dll', 'imm32.dll', 'iphlpapi.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'mpr.dll', 'msasn1.dll', 'msctf.dll', 'msvcrt.dll', 'mswsock.dll', 'msxml3.dll', 'msxml3r.dll', 'netapi32.dll', 'netutils.dll', 'nlaapi.dll', 'normaliz.dll', 'nsi.dll', 'ntdll.dll', 'ntlanman.dll', 'ntmarta.dll', 'ole32.dll', 'oleaut32.dll', 'peerdist.dll', 'profapi.dll', 'rasadhlp.dll', 'rasapi32.dll', 'rasman.dll', 'rpcrt4.dll', 'rpcrtremote.dll', 'rsaenh.dll', 'rtutils.dll', 'sechost.dll', 'sensapi.dll', 'shell32.dll', 'shlwapi.dll', 'srvcli.dll', 'sspicli.dll', 'urlmon.dll', 'user32.dll', 'userenv.dll', 'usp10.dll', 'uxtheme.dll', 'vboxmrxnp.dll', 'vssapi.dll', 'vsstrace.dll', 'wininet.dll', 'winnsi.dll', 'winsta.dll', 'wkscli.dll', 'wldap32.dll', 'ws2_32.dll', 'wshtcpip.dll'],
	['advapi32.dll', 'apisetschema.dll', 'authz.dll', 'browcli.dll', 'comctl32.dll', 'crypt32.dll', 'cryptbase.dll', 'cryptsp.dll', 'cscapi.dll', 'davclnt.dll', 'davhlpr.dll', 'dnsapi.dll', 'drprov.dll', 'dsrole.dll', 'gdi32.dll', 'iertutil.dll', 'imm32.dll', 'iphlpapi.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'mpr.dll', 'msasn1.dll', 'msctf.dll', 'msvcrt.dll', 'mswsock.dll', 'netapi32.dll', 'netutils.dll', 'nlaapi.dll', 'normaliz.dll', 'nsi.dll', 'ntdll.dll', 'ntlanman.dll', 'ntmarta.dll', 'ole32.dll', 'oleaut32.dll', 'peerdist.dll', 'profapi.dll', 'rasadhlp.dll', 'rasapi32.dll', 'rasman.dll', 'rpcrt4.dll', 'rsaenh.dll', 'rtutils.dll', 'sechost.dll', 'sensapi.dll', 'shell32.dll', 'shlwapi.dll', 'srvcli.dll', 'sspicli.dll', 'urlmon.dll', 'user32.dll', 'userenv.dll', 'usp10.dll', 'uxtheme.dll', 'vboxmrxnp.dll', 'wininet.dll', 'winnsi.dll', 'winsta.dll', 'wkscli.dll', 'wldap32.dll', 'ws2_32.dll', 'wshtcpip.dll'],
	['advapi32.dll', 'apisetschema.dll', 'authz.dll', 'browcli.dll', 'clbcatq.dll', 'comctl32.dll', 'crypt32.dll', 'cryptbase.dll', 'cryptsp.dll', 'cscapi.dll', 'davclnt.dll', 'davhlpr.dll', 'dnsapi.dll', 'drprov.dll', 'dsrole.dll', 'gdi32.dll', 'iertutil.dll', 'imm32.dll', 'iphlpapi.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'mpr.dll', 'msasn1.dll', 'msctf.dll', 'msvcrt.dll', 'mswsock.dll', 'netapi32.dll', 'netutils.dll', 'nlaapi.dll', 'normaliz.dll', 'nsi.dll', 'ntdll.dll', 'ntlanman.dll', 'ntmarta.dll', 'ole32.dll', 'oleaut32.dll', 'peerdist.dll', 'profapi.dll', 'rasadhlp.dll', 'rasapi32.dll', 'rasman.dll', 'rpcrt4.dll', 'rpcrtremote.dll', 'rsaenh.dll', 'rtutils.dll', 'sechost.dll', 'sensapi.dll', 'shell32.dll', 'shlwapi.dll', 'srvcli.dll', 'sspicli.dll', 'urlmon.dll', 'user32.dll', 'userenv.dll', 'usp10.dll', 'uxtheme.dll', 'vboxmrxnp.dll', 'vsstrace.dll', 'wininet.dll', 'winnsi.dll', 'winsta.dll', 'wkscli.dll', 'wldap32.dll', 'ws2_32.dll', 'wshtcpip.dll'],
	['advapi32.dll', 'apisetschema.dll', 'comctl32.dll', 'crypt32.dll', 'cryptbase.dll', 'cryptsp.dll', 'dnsapi.dll', 'dsrole.dll', 'gdi32.dll', 'iertutil.dll', 'imm32.dll', 'iphlpapi.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'mpr.dll', 'msasn1.dll', 'msctf.dll', 'msvcrt.dll', 'netapi32.dll', 'netutils.dll', 'normaliz.dll', 'nsi.dll', 'ntdll.dll', 'ntmarta.dll', 'ole32.dll', 'oleaut32.dll', 'profapi.dll', 'rpcrt4.dll', 'rsaenh.dll', 'sechost.dll', 'shell32.dll', 'shlwapi.dll', 'srvcli.dll', 'sspicli.dll', 'urlmon.dll', 'user32.dll', 'usp10.dll', 'uxtheme.dll', 'wininet.dll', 'winnsi.dll', 'wkscli.dll', 'wldap32.dll', 'ws2_32.dll'],
	['advapi32.dll', 'apisetschema.dll', 'apphelp.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcrt.dll', 'nsi.dll', 'ntdll.dll', 'rpcrt4.dll', 'sechost.dll', 'shell32.dll', 'shlwapi.dll', 'user32.dll', 'usp10.dll', 'ws2_32.dll', 'wsock32.dll'],
	['advapi32.dll', 'apisetschema.dll', 'apphelp.dll', 'cfgmgr32.dll', 'clbcatq.dll', 'comctl32.dll', 'cryptbase.dll', 'devobj.dll', 'dwmapi.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcrt.dll', 'nsi.dll', 'ntdll.dll', 'ntmarta.dll', 'ole32.dll', 'oleacc.dll', 'oleaccrc.dll', 'oleaut32.dll', 'profapi.dll', 'propsys.dll', 'psapi.dll', 'rpcrt4.dll', 'sechost.dll', 'setupapi.dll', 'shell32.dll', 'shfolder.dll', 'shlwapi.dll', 'system.dll', 'user32.dll', 'userenv.dll', 'usp10.dll', 'uxtheme.dll', 'version.dll', 'wldap32.dll', 'ws2_32.dll'],
	['advapi32.dll', 'apisetschema.dll', 'apphelp.dll', 'cryptbase.dll', 'cryptsp.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcrt.dll', 'ntdll.dll', 'rpcrt4.dll', 'rsaenh.dll', 'sechost.dll', 'shell32.dll', 'user32.dll', 'usp10.dll'],
	['advapi32.dll', 'apphelp.dll', 'cryptbase.dll', 'cryptsp.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcp60.dll', 'msvcrt.dll', 'ntdll.dll', 'ntmarta.dll', 'ole32.dll', 'rpcrt4.dll', 'rsaenh.dll', 'sechost.dll', 'shell32.dll', 'shlwapi.dll', 'user32.dll', 'usp10.dll', 'wldap32.dll'],
	['advapi32.dll', 'apphelp.dll', 'cryptbase.dll', 'cryptsp.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcp60.dll', 'msvcrt.dll', 'ntdll.dll', 'ntmarta.dll', 'ole32.dll', 'rpcrt4.dll', 'rsaenh.dll', 'sechost.dll', 'shell32.dll', 'shlwapi.dll', 'sspicli.dll', 'user32.dll', 'usp10.dll', 'wldap32.dll'],
	['advapi32.dll', 'apphelp.dll', 'authz.dll', 'comctl32.dll', 'crypt32.dll', 'cryptbase.dll', 'dnsapi.dll', 'fwpuclnt.dll', 'gdi32.dll', 'iertutil.dll', 'imm32.dll', 'iphlpapi.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msasn1.dll', 'msctf.dll', 'msvcrt.dll', 'mswsock.dll', 'napinsp.dll', 'nlaapi.dll', 'normaliz.dll', 'nsi.dll', 'ntdll.dll', 'ole32.dll', 'oleaut32.dll', 'peerdist.dll', 'pnrpnsp.dll', 'profapi.dll', 'rasadhlp.dll', 'rasapi32.dll', 'rasman.dll', 'rpcrt4.dll', 'rtutils.dll', 'sechost.dll', 'sensapi.dll', 'shell32.dll', 'shlwapi.dll', 'sspicli.dll', 'urlmon.dll', 'user32.dll', 'userenv.dll', 'usp10.dll', 'uxtheme.dll', 'wininet.dll', 'winnsi.dll', 'winrnr.dll', 'ws2_32.dll', 'wship6.dll', 'wshtcpip.dll', 'wsock32.dll'],
	['advapi32.dll', 'apphelp.dll', 'cfgmgr32.dll', 'clbcatq.dll', 'comctl32.dll', 'crypt32.dll', 'cryptbase.dll', 'cryptsp.dll', 'cscapi.dll', 'davclnt.dll', 'davhlpr.dll', 'devobj.dll', 'drprov.dll', 'dwmapi.dll', 'fastprox.dll', 'gdi32.dll', 'gdiplus.dll', 'iertutil.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'linkinfo.dll', 'lpk.dll', 'mpr.dll', 'msasn1.dll', 'msctf.dll', 'msvcrt.dll', 'mswsock.dll', 'netapi32.dll', 'netutils.dll', 'nsi.dll', 'ntdll.dll', 'ntdsapi.dll', 'ntlanman.dll', 'ntmarta.dll', 'ole32.dll', 'oleaut32.dll', 'powrprof.dll', 'profapi.dll', 'propsys.dll', 'rpcrt4.dll', 'rpcrtremote.dll', 'rsaenh.dll', 'samcli.dll', 'samlib.dll', 'searchfolder.dll', 'sechost.dll', 'setupapi.dll', 'shdocvw.dll', 'shell32.dll', 'shlwapi.dll', 'srvcli.dll', 'urlmon.dll', 'user32.dll', 'usp10.dll', 'uxtheme.dll', 'vboxmrxnp.dll', 'version.dll', 'wbemcomn.dll', 'wbemprox.dll', 'wbemsvc.dll', 'windowscodecs.dll', 'winsta.dll', 'wintrust.dll', 'wkscli.dll', 'wldap32.dll', 'ws2_32.dll', 'wshtcpip.dll', 'zipfldr.dll'],
	['advapi32.dll', 'apphelp.dll', 'cfgmgr32.dll', 'clbcatq.dll', 'comctl32.dll', 'cryptbase.dll', 'cryptsp.dll', 'devobj.dll', 'dwmapi.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcrt.dll', 'nsi.dll', 'ntdll.dll', 'ntmarta.dll', 'ole32.dll', 'oleacc.dll', 'oleaut32.dll', 'profapi.dll', 'propsys.dll', 'psapi.dll', 'rpcrt4.dll', 'rsaenh.dll', 'sechost.dll', 'setupapi.dll', 'shell32.dll', 'shfolder.dll', 'shlwapi.dll', 'system.dll', 'user32.dll', 'userenv.dll', 'usp10.dll', 'uxtheme.dll', 'version.dll', 'wldap32.dll', 'ws2_32.dll'],
	# =============
	['advapi32.dll', 'apisetschema.dll', 'clbcatq.dll', 'comctl32.dll', 'cryptbase.dll', 'dwmapi.dll', 'gdi32.dll', 'gdiplus.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcrt.dll', 'ntdll.dll', 'ole32.dll', 'oleacc.dll', 'oleaccrc.dll', 'oleaut32.dll', 'rpcrt4.dll', 'sechost.dll', 'shell32.dll', 'shlwapi.dll', 'user32.dll', 'usp10.dll', 'uxtheme.dll', 'version.dll', 'windowscodecs.dll', 'winmm.dll'], # calc.exe
	['advapi32.dll', 'apisetschema.dll', 'comctl32.dll', 'comdlg32.dll', 'cryptbase.dll', 'dwmapi.dll', 'gdi32.dll', 'imm32.dll', 'kernel32.dll', 'kernelbase.dll', 'lpk.dll', 'msctf.dll', 'msvcrt.dll', 'ntdll.dll', 'ole32.dll', 'oleaut32.dll', 'rpcrt4.dll', 'sechost.dll', 'shell32.dll', 'shlwapi.dll', 'user32.dll', 'usp10.dll', 'uxtheme.dll', 'version.dll'], # notepad.exe
	['oleaut32.dll', 'advapi32.dll', 'msvcrt.dll', 'ntdll.dll', 'dwmapi.dll', 'shlwapi.dll', 'gdiplus.dll', 'gdi32.dll', 'version.dll', 'kernel32.dll', 'oleacc.dll', 'comctl32.dll', 'windowscodecs.dll', 'usp10.dll', 'user32.dll', 'shell32.dll', 'rpcrt4.dll', 'clbcatq.dll', 'apisetschema.dll', 'cryptbase.dll', 'sechost.dll', 'oleaccrc.dll', 'imm32.dll', 'lpk.dll', 'msctf.dll', 'ole32.dll', 'winmm.dll', 'kernelbase.dll', 'uxtheme.dll'], # calc.exe
	['oleaut32.dll', 'advapi32.dll', 'msvcrt.dll', 'sechost.dll', 'comdlg32.dll', 'kernel32.dll', 'ntdll.dll', 'dwmapi.dll', 'shlwapi.dll', 'gdi32.dll', 'version.dll', 'apisetschema.dll', 'comctl32.dll', 'usp10.dll', 'user32.dll', 'shell32.dll', 'rpcrt4.dll', 'cryptbase.dll', 'imm32.dll', 'lpk.dll', 'msctf.dll', 'ole32.dll', 'kernelbase.dll', 'uxtheme.dll'], # notepad.exe


] # Copy new data LIST TO MYDB.PY



['mscoree.dll', 'advapi32.dll', 'msvcrt.dll', 'sechost.dll', 'ntdll.dll', 'shlwapi.dll', 'profapi.dll', 'mscoreei.dll', 'gdi32.dll', 'apisetschema.dll', 'mscorwks.dll', 'user32.dll', 'shell32.dll', 'rpcrt4.dll', 'ole32.dll', 'usp10.dll', 'msvcr80.dll', 'imm32.dll', 'lpk.dll', 'msctf.dll', 'kernel32.dll', 'kernelbase.dll'], # ransom-jigsaw.exe
['mscoree.dll', 'advapi32.dll', 'msvcrt.dll', 'sechost.dll', 'mscorwks.dll', 'shlwapi.dll', 'profapi.dll', 'mscoreei.dll', 'gdi32.dll', 'apisetschema.dll', 'ntdll.dll', 'mscorlib.ni.dll', 'usp10.dll', 'user32.dll', 'shell32.dll', 'rpcrt4.dll', 'ole32.dll', 'cryptbase.dll', 'msvcr80.dll', 'imm32.dll', 'lpk.dll', 'msctf.dll', 'kernel32.dll', 'kernelbase.dll', 'uxtheme.dll'], # ransom-jigsaw.exe
['usp10.dll', 'ws2_32.dll', 'user32.dll', 'imm32.dll', 'rtutils.dll', 'lpk.dll', 'nsi.dll', 'msctf.dll', 'apisetschema.dll', 'advapi32.dll', 'msvcrt.dll', 'sechost.dll', 'gdi32.dll', 'ntdll.dll', 'kernel32.dll', 'rasapi32.dll', 'rasman.dll', 'kernelbase.dll', 'rpcrt4.dll'], # ransom-locky.exe
['usp10.dll', 'user32.dll', 'imm32.dll', 'rpcrt4.dll', 'lpk.dll', 'clusapi.dll', 'advapi32.dll', 'cryptdll.dll', 'msvcrt.dll', 'sechost.dll', 'gdi32.dll', 'msctf.dll', 'kernel32.dll', 'apisetschema.dll', 'kernelbase.dll', 'dbghelp.dll', 'ntdll.dll'], # ransom-matsnu.com
['mscoree.dll', 'advapi32.dll', 'msvcrt.dll', 'msvcr80.dll', 'mscorwks.dll', 'mscorjit.dll', 'profapi.dll', 'mscoreei.dll', 'gdi32.dll', 'apisetschema.dll', 'ntdll.dll', 'mscorlib.ni.dll', 'usp10.dll', 'user32.dll', 'shell32.dll', 'rpcrt4.dll', 'ole32.dll', 'cryptbase.dll', 'sechost.dll', 'imm32.dll', 'lpk.dll', 'msctf.dll', 'shlwapi.dll', 'kernel32.dll', 'kernelbase.dll', 'uxtheme.dll'], # ransom-petrwrap-2.exe
['oleaut32.dll', 'advapi32.dll', 'msvcrt.dll', 'sechost.dll', 'ntdll.dll', 'quartz.dll', 'shlwapi.dll', 'gdi32.dll', 'apisetschema.dll', 'usp10.dll', 'user32.dll', 'shell32.dll', 'rpcrt4.dll', 'ole32.dll', 'cryptbase.dll', 'clbcatq.dll', 'imm32.dll', 'lpk.dll', 'winmm.dll', 'msctf.dll', 'kernel32.dll', 'kernelbase.dll', 'uxtheme.dll'], # ransom-teslacrypt-2.exe
['usp10.dll', 'user32.dll', 'imm32.dll', 'rpcrt4.dll', 'lpk.dll', 'msctf.dll', 'advapi32.dll', 'msvcrt.dll', 'sechost.dll', 'gdi32.dll', 'kernel32.dll', 'apisetschema.dll', 'kernelbase.dll', 'ntdll.dll'], # ransom-wannacry.exe
['oleaut32.dll', 'urlmon.dll', 'odbc32.dll', 'mfc42.dll.mui', 'advapi32.dll', 'msvcrt.dll', 'sechost.dll', 'msasn1.dll', 'iertutil.dll', 'rpcrt4.dll', 'odbcint.dll.mui', 'dwmapi.dll', 'mfc42.dll', 'shlwapi.dll', 'riched32.dll', 'gdi32.dll', 'apisetschema.dll', 'ntdll.dll', 'comctl32.dll', 'windowscodecs.dll', 'user32.dll', 'shell32.dll', 'kernel32.dll', 'wininet.dll', 'msvcp60.dll', 'crypt32.dll', 'nsi.dll', 'riched20.dll', 'usp10.dll', 'ws2_32.dll', 'imm32.dll', 'lpk.dll', 'odbcint.dll', 'msctf.dll', 'ole32.dll', 'normaliz.dll', 'kernelbase.dll', 'iconcodecservice.dll', 'uxtheme.dll'], # @wanadecryptor@.exe



